### ISSUE TITLE
Epic : Implement W3C validation tests

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csvw-check#58]
- [x]   Validate CSV-W without a metadata https://app.zenhub.com/workspaces/cogs-utils-60d4aba8ecae03000e18503d/issues/gss-cogs/csv-validation/70
- [x]   Add definitions for steps (cucumber step definitions). The final steps are missing now. Make any changes to others steps as well if needed
- [x]   Add in any other functionality missing, fix bugs to make the W3C Validation tests pass
