### ISSUE TITLE
Epic: CSV Validation 

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csvw-check#7]
- [x] #56  Implement parse contents function
- [x] #54 Ensure column data type is validated
- [x] #57 Implement validate function
- [x] #55 Test the implemented code against some examples
